--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-07-21 10:20:34

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16389)
-- Name: question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.question (
    id integer NOT NULL,
    category character varying(255),
    difficultylevel character varying(255),
    option1 character varying(255),
    option2 character varying(255),
    option3 character varying(255),
    option4 character varying(255),
    question_title character varying(255),
    right_answer character varying(255)
);


ALTER TABLE public.question OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16431)
-- Name: question_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.question_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.question_seq OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16445)
-- Name: quiz; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz (
    id integer NOT NULL,
    title character varying(255)
);


ALTER TABLE public.quiz OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16444)
-- Name: quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quiz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16450)
-- Name: quiz_questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_questions (
    quiz_id integer NOT NULL,
    questions_id integer NOT NULL
);


ALTER TABLE public.quiz_questions OWNER TO postgres;

--
-- TOC entry 4751 (class 2604 OID 16443)
-- Name: question id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question ALTER COLUMN id SET DEFAULT nextval('public.id'::regclass);


--
-- TOC entry 4903 (class 0 OID 16389)
-- Dependencies: 217
-- Data for Name: question; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.question (id, category, difficultylevel, option1, option2, option3, option4, question_title, right_answer) FROM stdin;
1	Java	Easy	class	interface	extends	implements	Which java keyword is used to create subclass	extends
2	Java	Easy	4	5	6	compiler error	Which is output for following code	5
3	Java	Easy	true	false	0	null	default value for uninitialised boolean	false
4	Java	Easy	try	throw	catch	finally	Java keyword used to throw exception	throw
5	Java	Easy	it indicates tghat a variable is constant	a method can be accessed	a class can be accessed	indicates variable of prim type	Static keyword mean in java	Indicates method that access without object
6	Java	Easy	constant int x=5	final int x=5	static int x=5	readonly int x=5	Correct way of declaring constant var	final int x=5
7	Java	Easy	for loop	while loop	do-while loop	switch loop	Loop allowed to executes atleast once	do-while loop
8	python	Easy	1	2	3	4	Maximum value for short in python	3
9	Java	Easy	1	2	3	4	Maximum value for short in Java	3
10	Java	Easy	Bool	Float	String	Double	What is return type of toString	String
11	python	Easy	fun	def	class	room	How to define class in python	def
12	python	Easy	snake	Language	programming Language	reptile	what is python	programming Language
\.


--
-- TOC entry 4906 (class 0 OID 16445)
-- Dependencies: 220
-- Data for Name: quiz; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz (id, title) FROM stdin;
1	JQuiz
\.


--
-- TOC entry 4907 (class 0 OID 16450)
-- Dependencies: 221
-- Data for Name: quiz_questions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz_questions (quiz_id, questions_id) FROM stdin;
1	10
1	1
1	3
1	7
1	6
\.


--
-- TOC entry 4913 (class 0 OID 0)
-- Dependencies: 218
-- Name: question_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.question_seq', 151, true);


--
-- TOC entry 4914 (class 0 OID 0)
-- Dependencies: 219
-- Name: quiz_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quiz_id_seq', 1, true);


--
-- TOC entry 4753 (class 2606 OID 16441)
-- Name: question id; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT id PRIMARY KEY (id);


--
-- TOC entry 4755 (class 2606 OID 16449)
-- Name: quiz quiz_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz
    ADD CONSTRAINT quiz_pkey PRIMARY KEY (id);


--
-- TOC entry 4756 (class 2606 OID 16458)
-- Name: quiz_questions fkcgp9e1c6ww3t383aui4w8feae; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_questions
    ADD CONSTRAINT fkcgp9e1c6ww3t383aui4w8feae FOREIGN KEY (quiz_id) REFERENCES public.quiz(id);


--
-- TOC entry 4757 (class 2606 OID 16453)
-- Name: quiz_questions fkpmfvwer12y1nrjc0efm04dq16; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_questions
    ADD CONSTRAINT fkpmfvwer12y1nrjc0efm04dq16 FOREIGN KEY (questions_id) REFERENCES public.question(id);


-- Completed on 2025-07-21 10:20:35

--
-- PostgreSQL database dump complete
--

