--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-07-21 10:22:42

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16465)
-- Name: quiz; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz (
    id integer NOT NULL,
    title character varying(255)
);


ALTER TABLE public.quiz OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16464)
-- Name: quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quiz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16470)
-- Name: quiz_question_ids; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_question_ids (
    quiz_id integer NOT NULL,
    question_ids integer
);


ALTER TABLE public.quiz_question_ids OWNER TO postgres;

--
-- TOC entry 4895 (class 0 OID 16465)
-- Dependencies: 218
-- Data for Name: quiz; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz (id, title) FROM stdin;
1	Springers Quiz 1
\.


--
-- TOC entry 4896 (class 0 OID 16470)
-- Dependencies: 219
-- Data for Name: quiz_question_ids; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz_question_ids (quiz_id, question_ids) FROM stdin;
1	3
1	4
1	7
1	6
1	5
\.


--
-- TOC entry 4902 (class 0 OID 0)
-- Dependencies: 217
-- Name: quiz_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quiz_id_seq', 1, true);


--
-- TOC entry 4747 (class 2606 OID 16469)
-- Name: quiz quiz_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz
    ADD CONSTRAINT quiz_pkey PRIMARY KEY (id);


--
-- TOC entry 4748 (class 2606 OID 16473)
-- Name: quiz_question_ids fks0d7k0yq779g15wmctr0tlnbi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_question_ids
    ADD CONSTRAINT fks0d7k0yq779g15wmctr0tlnbi FOREIGN KEY (quiz_id) REFERENCES public.quiz(id);


-- Completed on 2025-07-21 10:22:42

--
-- PostgreSQL database dump complete
--

